// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcResponse.proto

package cn.jiuyou2020.serialize.message;

public final class RpcResponseOuterClass {
  private RpcResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcResponseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.jiuyou2020.serialize.message.RpcResponseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes result = 1;</code>
     * @return The result.
     */
    com.google.protobuf.ByteString getResult();

    /**
     * <pre>
     * New field for return type
     * </pre>
     *
     * <code>string returnType = 2;</code>
     * @return The returnType.
     */
    String getReturnType();
    /**
     * <pre>
     * New field for return type
     * </pre>
     *
     * <code>string returnType = 2;</code>
     * @return The bytes for returnType.
     */
    com.google.protobuf.ByteString
        getReturnTypeBytes();

    /**
     * <code>string errorMessage = 3;</code>
     * @return The errorMessage.
     */
    String getErrorMessage();
    /**
     * <code>string errorMessage = 3;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code cn.jiuyou2020.serialize.message.RpcResponseProto}
   */
  public static final class RpcResponseProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.jiuyou2020.serialize.message.RpcResponseProto)
      RpcResponseProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RpcResponseProto.newBuilder() to construct.
    private RpcResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcResponseProto() {
      result_ = com.google.protobuf.ByteString.EMPTY;
      returnType_ = "";
      errorMessage_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RpcResponseProto();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcResponseOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcResponseOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcResponseProto.class, Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes result = 1;</code>
     * @return The result.
     */
    @Override
    public com.google.protobuf.ByteString getResult() {
      return result_;
    }

    public static final int RETURNTYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object returnType_ = "";
    /**
     * <pre>
     * New field for return type
     * </pre>
     *
     * <code>string returnType = 2;</code>
     * @return The returnType.
     */
    @Override
    public String getReturnType() {
      Object ref = returnType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        returnType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * New field for return type
     * </pre>
     *
     * <code>string returnType = 2;</code>
     * @return The bytes for returnType.
     */
    @Override
    public com.google.protobuf.ByteString
        getReturnTypeBytes() {
      Object ref = returnType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        returnType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object errorMessage_ = "";
    /**
     * <code>string errorMessage = 3;</code>
     * @return The errorMessage.
     */
    @Override
    public String getErrorMessage() {
      Object ref = errorMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string errorMessage = 3;</code>
     * @return The bytes for errorMessage.
     */
    @Override
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!result_.isEmpty()) {
        output.writeBytes(1, result_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(returnType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, returnType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!result_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, result_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(returnType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, returnType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcResponseProto)) {
        return super.equals(obj);
      }
      RpcResponseProto other = (RpcResponseProto) obj;

      if (!getResult()
          .equals(other.getResult())) return false;
      if (!getReturnType()
          .equals(other.getReturnType())) return false;
      if (!getErrorMessage()
          .equals(other.getErrorMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (37 * hash) + RETURNTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReturnType().hashCode();
      hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcResponseProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponseProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcResponseProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.jiuyou2020.serialize.message.RpcResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.jiuyou2020.serialize.message.RpcResponseProto)
        RpcResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcResponseOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcResponseOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcResponseProto.class, Builder.class);
      }

      // Construct using cn.jiuyou2020.serialize.message.RpcResponseOuterClass.RpcResponseProto.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = com.google.protobuf.ByteString.EMPTY;
        returnType_ = "";
        errorMessage_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcResponseOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_descriptor;
      }

      @Override
      public RpcResponseProto getDefaultInstanceForType() {
        return RpcResponseProto.getDefaultInstance();
      }

      @Override
      public RpcResponseProto build() {
        RpcResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RpcResponseProto buildPartial() {
        RpcResponseProto result = new RpcResponseProto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(RpcResponseProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.returnType_ = returnType_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.errorMessage_ = errorMessage_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcResponseProto) {
          return mergeFrom((RpcResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcResponseProto other) {
        if (other == RpcResponseProto.getDefaultInstance()) return this;
        if (other.getResult() != com.google.protobuf.ByteString.EMPTY) {
          setResult(other.getResult());
        }
        if (!other.getReturnType().isEmpty()) {
          returnType_ = other.returnType_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getErrorMessage().isEmpty()) {
          errorMessage_ = other.errorMessage_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                result_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                returnType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                errorMessage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes result = 1;</code>
       * @return The result.
       */
      @Override
      public com.google.protobuf.ByteString getResult() {
        return result_;
      }
      /**
       * <code>bytes result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }

      private Object returnType_ = "";
      /**
       * <pre>
       * New field for return type
       * </pre>
       *
       * <code>string returnType = 2;</code>
       * @return The returnType.
       */
      public String getReturnType() {
        Object ref = returnType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          returnType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * New field for return type
       * </pre>
       *
       * <code>string returnType = 2;</code>
       * @return The bytes for returnType.
       */
      public com.google.protobuf.ByteString
          getReturnTypeBytes() {
        Object ref = returnType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          returnType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * New field for return type
       * </pre>
       *
       * <code>string returnType = 2;</code>
       * @param value The returnType to set.
       * @return This builder for chaining.
       */
      public Builder setReturnType(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        returnType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * New field for return type
       * </pre>
       *
       * <code>string returnType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReturnType() {
        returnType_ = getDefaultInstance().getReturnType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * New field for return type
       * </pre>
       *
       * <code>string returnType = 2;</code>
       * @param value The bytes for returnType to set.
       * @return This builder for chaining.
       */
      public Builder setReturnTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        returnType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object errorMessage_ = "";
      /**
       * <code>string errorMessage = 3;</code>
       * @return The errorMessage.
       */
      public String getErrorMessage() {
        Object ref = errorMessage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string errorMessage = 3;</code>
       * @return The bytes for errorMessage.
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorMessage = 3;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        errorMessage_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string errorMessage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        errorMessage_ = getDefaultInstance().getErrorMessage();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string errorMessage = 3;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        errorMessage_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.jiuyou2020.serialize.message.RpcResponseProto)
    }

    // @@protoc_insertion_point(class_scope:cn.jiuyou2020.serialize.message.RpcResponseProto)
    private static final RpcResponseProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcResponseProto();
    }

    public static RpcResponseProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcResponseProto>
        PARSER = new com.google.protobuf.AbstractParser<RpcResponseProto>() {
      @Override
      public RpcResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RpcResponseProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcResponseProto> getParserForType() {
      return PARSER;
    }

    @Override
    public RpcResponseProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021RpcResponse.proto\022\037cn.jiuyou2020.seria" +
      "lize.message\"L\n\020RpcResponseProto\022\016\n\006resu" +
      "lt\030\001 \001(\014\022\022\n\nreturnType\030\002 \001(\t\022\024\n\014errorMes" +
      "sage\030\003 \001(\tB\027B\025RpcResponseOuterClassb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_jiuyou2020_serialize_message_RpcResponseProto_descriptor,
        new String[] { "Result", "ReturnType", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
