spring:
  # redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456789
    timeout: 10000
    database: 0
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

server:
  port: 8081