// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SerializationData.proto

package cn.jiuyou2020.serialize;

public final class SerializationDataOuterClass {
  private SerializationDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SerializationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.jiuyou2020.serialize.SerializationData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string className = 1;</code>
     * @return The className.
     */
    java.lang.String getClassName();
    /**
     * <code>string className = 1;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated string parameterTypes = 3;</code>
     * @return A list containing the parameterTypes.
     */
    java.util.List<java.lang.String>
        getParameterTypesList();
    /**
     * <code>repeated string parameterTypes = 3;</code>
     * @return The count of parameterTypes.
     */
    int getParameterTypesCount();
    /**
     * <code>repeated string parameterTypes = 3;</code>
     * @param index The index of the element to return.
     * @return The parameterTypes at the given index.
     */
    java.lang.String getParameterTypes(int index);
    /**
     * <code>repeated string parameterTypes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterTypes at the given index.
     */
    com.google.protobuf.ByteString
        getParameterTypesBytes(int index);

    /**
     * <code>repeated string args = 4;</code>
     * @return A list containing the args.
     */
    java.util.List<java.lang.String>
        getArgsList();
    /**
     * <code>repeated string args = 4;</code>
     * @return The count of args.
     */
    int getArgsCount();
    /**
     * <code>repeated string args = 4;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    java.lang.String getArgs(int index);
    /**
     * <code>repeated string args = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the args at the given index.
     */
    com.google.protobuf.ByteString
        getArgsBytes(int index);
  }
  /**
   * Protobuf type {@code cn.jiuyou2020.serialize.SerializationData}
   */
  public static final class SerializationData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.jiuyou2020.serialize.SerializationData)
      SerializationDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SerializationData.newBuilder() to construct.
    private SerializationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SerializationData() {
      className_ = "";
      methodName_ = "";
      parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SerializationData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.jiuyou2020.serialize.SerializationDataOuterClass.internal_static_cn_jiuyou2020_serialize_SerializationData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.jiuyou2020.serialize.SerializationDataOuterClass.internal_static_cn_jiuyou2020_serialize_SerializationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData.class, cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData.Builder.class);
    }

    public static final int CLASSNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object className_ = "";
    /**
     * <code>string className = 1;</code>
     * @return The className.
     */
    @java.lang.Override
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <code>string className = 1;</code>
     * @return The bytes for className.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object methodName_ = "";
    /**
     * <code>string methodName = 2;</code>
     * @return The methodName.
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string methodName = 2;</code>
     * @return The bytes for methodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERTYPES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList parameterTypes_;
    /**
     * <code>repeated string parameterTypes = 3;</code>
     * @return A list containing the parameterTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getParameterTypesList() {
      return parameterTypes_;
    }
    /**
     * <code>repeated string parameterTypes = 3;</code>
     * @return The count of parameterTypes.
     */
    public int getParameterTypesCount() {
      return parameterTypes_.size();
    }
    /**
     * <code>repeated string parameterTypes = 3;</code>
     * @param index The index of the element to return.
     * @return The parameterTypes at the given index.
     */
    public java.lang.String getParameterTypes(int index) {
      return parameterTypes_.get(index);
    }
    /**
     * <code>repeated string parameterTypes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getParameterTypesBytes(int index) {
      return parameterTypes_.getByteString(index);
    }

    public static final int ARGS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList args_;
    /**
     * <code>repeated string args = 4;</code>
     * @return A list containing the args.
     */
    public com.google.protobuf.ProtocolStringList
        getArgsList() {
      return args_;
    }
    /**
     * <code>repeated string args = 4;</code>
     * @return The count of args.
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated string args = 4;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    public java.lang.String getArgs(int index) {
      return args_.get(index);
    }
    /**
     * <code>repeated string args = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the args at the given index.
     */
    public com.google.protobuf.ByteString
        getArgsBytes(int index) {
      return args_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, className_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      for (int i = 0; i < parameterTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parameterTypes_.getRaw(i));
      }
      for (int i = 0; i < args_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, args_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, className_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameterTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(parameterTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParameterTypesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < args_.size(); i++) {
          dataSize += computeStringSizeNoTag(args_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getArgsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData)) {
        return super.equals(obj);
      }
      cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData other = (cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData) obj;

      if (!getClassName()
          .equals(other.getClassName())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParameterTypesList()
          .equals(other.getParameterTypesList())) return false;
      if (!getArgsList()
          .equals(other.getArgsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      if (getParameterTypesCount() > 0) {
        hash = (37 * hash) + PARAMETERTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getParameterTypesList().hashCode();
      }
      if (getArgsCount() > 0) {
        hash = (37 * hash) + ARGS_FIELD_NUMBER;
        hash = (53 * hash) + getArgsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.jiuyou2020.serialize.SerializationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.jiuyou2020.serialize.SerializationData)
        cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.jiuyou2020.serialize.SerializationDataOuterClass.internal_static_cn_jiuyou2020_serialize_SerializationData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.jiuyou2020.serialize.SerializationDataOuterClass.internal_static_cn_jiuyou2020_serialize_SerializationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData.class, cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData.Builder.class);
      }

      // Construct using cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        className_ = "";
        methodName_ = "";
        parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.jiuyou2020.serialize.SerializationDataOuterClass.internal_static_cn_jiuyou2020_serialize_SerializationData_descriptor;
      }

      @java.lang.Override
      public cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData getDefaultInstanceForType() {
        return cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData.getDefaultInstance();
      }

      @java.lang.Override
      public cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData build() {
        cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData buildPartial() {
        cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData result = new cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData result) {
        if (((bitField0_ & 0x00000004) != 0)) {
          parameterTypes_ = parameterTypes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parameterTypes_ = parameterTypes_;
        if (((bitField0_ & 0x00000008) != 0)) {
          args_ = args_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.args_ = args_;
      }

      private void buildPartial0(cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.className_ = className_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.methodName_ = methodName_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData) {
          return mergeFrom((cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData other) {
        if (other == cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData.getDefaultInstance()) return this;
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.parameterTypes_.isEmpty()) {
          if (parameterTypes_.isEmpty()) {
            parameterTypes_ = other.parameterTypes_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParameterTypesIsMutable();
            parameterTypes_.addAll(other.parameterTypes_);
          }
          onChanged();
        }
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                className_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                methodName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureParameterTypesIsMutable();
                parameterTypes_.add(s);
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureArgsIsMutable();
                args_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object className_ = "";
      /**
       * <code>string className = 1;</code>
       * @return The className.
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string className = 1;</code>
       * @return The bytes for className.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string className = 1;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        className_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string className = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        className_ = getDefaultInstance().getClassName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string className = 1;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        className_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string methodName = 2;</code>
       * @return The methodName.
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string methodName = 2;</code>
       * @return The bytes for methodName.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string methodName = 2;</code>
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        methodName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        methodName_ = getDefaultInstance().getMethodName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string methodName = 2;</code>
       * @param value The bytes for methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        methodName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParameterTypesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          parameterTypes_ = new com.google.protobuf.LazyStringArrayList(parameterTypes_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @return A list containing the parameterTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getParameterTypesList() {
        return parameterTypes_.getUnmodifiableView();
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @return The count of parameterTypes.
       */
      public int getParameterTypesCount() {
        return parameterTypes_.size();
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @param index The index of the element to return.
       * @return The parameterTypes at the given index.
       */
      public java.lang.String getParameterTypes(int index) {
        return parameterTypes_.get(index);
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the parameterTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getParameterTypesBytes(int index) {
        return parameterTypes_.getByteString(index);
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @param index The index to set the value at.
       * @param value The parameterTypes to set.
       * @return This builder for chaining.
       */
      public Builder setParameterTypes(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParameterTypesIsMutable();
        parameterTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @param value The parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParameterTypes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureParameterTypesIsMutable();
        parameterTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @param values The parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllParameterTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureParameterTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameterTypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParameterTypes() {
        parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameterTypes = 3;</code>
       * @param value The bytes of the parameterTypes to add.
       * @return This builder for chaining.
       */
      public Builder addParameterTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureParameterTypesIsMutable();
        parameterTypes_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArgsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          args_ = new com.google.protobuf.LazyStringArrayList(args_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string args = 4;</code>
       * @return A list containing the args.
       */
      public com.google.protobuf.ProtocolStringList
          getArgsList() {
        return args_.getUnmodifiableView();
      }
      /**
       * <code>repeated string args = 4;</code>
       * @return The count of args.
       */
      public int getArgsCount() {
        return args_.size();
      }
      /**
       * <code>repeated string args = 4;</code>
       * @param index The index of the element to return.
       * @return The args at the given index.
       */
      public java.lang.String getArgs(int index) {
        return args_.get(index);
      }
      /**
       * <code>repeated string args = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the args at the given index.
       */
      public com.google.protobuf.ByteString
          getArgsBytes(int index) {
        return args_.getByteString(index);
      }
      /**
       * <code>repeated string args = 4;</code>
       * @param index The index to set the value at.
       * @param value The args to set.
       * @return This builder for chaining.
       */
      public Builder setArgs(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string args = 4;</code>
       * @param value The args to add.
       * @return This builder for chaining.
       */
      public Builder addArgs(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string args = 4;</code>
       * @param values The args to add.
       * @return This builder for chaining.
       */
      public Builder addAllArgs(
          java.lang.Iterable<java.lang.String> values) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string args = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearArgs() {
        args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string args = 4;</code>
       * @param value The bytes of the args to add.
       * @return This builder for chaining.
       */
      public Builder addArgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.jiuyou2020.serialize.SerializationData)
    }

    // @@protoc_insertion_point(class_scope:cn.jiuyou2020.serialize.SerializationData)
    private static final cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData();
    }

    public static cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SerializationData>
        PARSER = new com.google.protobuf.AbstractParser<SerializationData>() {
      @java.lang.Override
      public SerializationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SerializationData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SerializationData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.jiuyou2020.serialize.SerializationDataOuterClass.SerializationData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_jiuyou2020_serialize_SerializationData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_jiuyou2020_serialize_SerializationData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027SerializationData.proto\022\027cn.jiuyou2020" +
      ".serialize\"`\n\021SerializationData\022\021\n\tclass" +
      "Name\030\001 \001(\t\022\022\n\nmethodName\030\002 \001(\t\022\026\n\016parame" +
      "terTypes\030\003 \003(\t\022\014\n\004args\030\004 \003(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_jiuyou2020_serialize_SerializationData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_jiuyou2020_serialize_SerializationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_jiuyou2020_serialize_SerializationData_descriptor,
        new java.lang.String[] { "ClassName", "MethodName", "ParameterTypes", "Args", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
