// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcRequest.proto

package cn.jiuyou2020.serialize.message.protobuf;

public final class RpcRequestOuterClass {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\020RpcRequest.proto\022\037cn.jiuyou2020.serial" +
                        "ize.message\"d\n\017RpcRequestProto\022\021\n\tclassN" +
                        "ame\030\001 \001(\t\022\022\n\nmethodName\030\002 \001(\t\022\026\n\016paramet" +
                        "erTypes\030\003 \003(\t\022\022\n\nparameters\030\004 \003(\014B\026B\024Rpc" +
                        "RequestOuterClassb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_descriptor,
                new String[]{"ClassName", "MethodName", "ParameterTypes", "Parameters",});
    }

    private RpcRequestOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface RpcRequestProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:cn.jiuyou2020.serialize.message.RpcRequestProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * New field for class type
         * </pre>
         *
         * <code>string className = 1;</code>
         *
         * @return The className.
         */
        String getClassName();

        /**
         * <pre>
         * New field for class type
         * </pre>
         *
         * <code>string className = 1;</code>
         *
         * @return The bytes for className.
         */
        com.google.protobuf.ByteString
        getClassNameBytes();

        /**
         * <code>string methodName = 2;</code>
         *
         * @return The methodName.
         */
        String getMethodName();

        /**
         * <code>string methodName = 2;</code>
         *
         * @return The bytes for methodName.
         */
        com.google.protobuf.ByteString
        getMethodNameBytes();

        /**
         * <code>repeated string parameterTypes = 3;</code>
         *
         * @return A list containing the parameterTypes.
         */
        java.util.List<String>
        getParameterTypesList();

        /**
         * <code>repeated string parameterTypes = 3;</code>
         *
         * @return The count of parameterTypes.
         */
        int getParameterTypesCount();

        /**
         * <code>repeated string parameterTypes = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The parameterTypes at the given index.
         */
        String getParameterTypes(int index);

        /**
         * <code>repeated string parameterTypes = 3;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the parameterTypes at the given index.
         */
        com.google.protobuf.ByteString
        getParameterTypesBytes(int index);

        /**
         * <code>repeated bytes parameters = 4;</code>
         *
         * @return A list containing the parameters.
         */
        java.util.List<com.google.protobuf.ByteString> getParametersList();

        /**
         * <code>repeated bytes parameters = 4;</code>
         *
         * @return The count of parameters.
         */
        int getParametersCount();

        /**
         * <code>repeated bytes parameters = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The parameters at the given index.
         */
        com.google.protobuf.ByteString getParameters(int index);
    }

    /**
     * Protobuf type {@code cn.jiuyou2020.serialize.message.RpcRequestProto}
     */
    public static final class RpcRequestProto extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:cn.jiuyou2020.serialize.message.RpcRequestProto)
            RpcRequestProtoOrBuilder {
        public static final int CLASSNAME_FIELD_NUMBER = 1;
        public static final int METHODNAME_FIELD_NUMBER = 2;
        public static final int PARAMETERTYPES_FIELD_NUMBER = 3;
        public static final int PARAMETERS_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:cn.jiuyou2020.serialize.message.RpcRequestProto)
        private static final RpcRequestProto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<RpcRequestProto>
                PARSER = new com.google.protobuf.AbstractParser<RpcRequestProto>() {
            @Override
            public RpcRequestProto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            DEFAULT_INSTANCE = new RpcRequestProto();
        }

        @SuppressWarnings("serial")
        private volatile Object className_ = "";
        @SuppressWarnings("serial")
        private volatile Object methodName_ = "";
        @SuppressWarnings("serial")
        private com.google.protobuf.LazyStringList parameterTypes_;
        @SuppressWarnings("serial")
        private java.util.List<com.google.protobuf.ByteString> parameters_;
        private byte memoizedIsInitialized = -1;

        // Use RpcRequestProto.newBuilder() to construct.
        private RpcRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RpcRequestProto() {
            className_ = "";
            methodName_ = "";
            parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            parameters_ = java.util.Collections.emptyList();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RpcRequestOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_descriptor;
        }

        public static RpcRequestProto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RpcRequestProto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RpcRequestProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RpcRequestProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RpcRequestProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static RpcRequestProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static RpcRequestProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static RpcRequestProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static RpcRequestProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static RpcRequestProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static RpcRequestProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static RpcRequestProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(RpcRequestProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static RpcRequestProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<RpcRequestProto> parser() {
            return PARSER;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new RpcRequestProto();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RpcRequestOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            RpcRequestProto.class, Builder.class);
        }

        /**
         * <pre>
         * New field for class type
         * </pre>
         *
         * <code>string className = 1;</code>
         *
         * @return The className.
         */
        @Override
        public String getClassName() {
            Object ref = className_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                className_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * New field for class type
         * </pre>
         *
         * <code>string className = 1;</code>
         *
         * @return The bytes for className.
         */
        @Override
        public com.google.protobuf.ByteString
        getClassNameBytes() {
            Object ref = className_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                className_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string methodName = 2;</code>
         *
         * @return The methodName.
         */
        @Override
        public String getMethodName() {
            Object ref = methodName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                methodName_ = s;
                return s;
            }
        }

        /**
         * <code>string methodName = 2;</code>
         *
         * @return The bytes for methodName.
         */
        @Override
        public com.google.protobuf.ByteString
        getMethodNameBytes() {
            Object ref = methodName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                methodName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated string parameterTypes = 3;</code>
         *
         * @return A list containing the parameterTypes.
         */
        public com.google.protobuf.ProtocolStringList
        getParameterTypesList() {
            return parameterTypes_;
        }

        /**
         * <code>repeated string parameterTypes = 3;</code>
         *
         * @return The count of parameterTypes.
         */
        public int getParameterTypesCount() {
            return parameterTypes_.size();
        }

        /**
         * <code>repeated string parameterTypes = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The parameterTypes at the given index.
         */
        public String getParameterTypes(int index) {
            return parameterTypes_.get(index);
        }

        /**
         * <code>repeated string parameterTypes = 3;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the parameterTypes at the given index.
         */
        public com.google.protobuf.ByteString
        getParameterTypesBytes(int index) {
            return parameterTypes_.getByteString(index);
        }

        /**
         * <code>repeated bytes parameters = 4;</code>
         *
         * @return A list containing the parameters.
         */
        @Override
        public java.util.List<com.google.protobuf.ByteString>
        getParametersList() {
            return parameters_;
        }

        /**
         * <code>repeated bytes parameters = 4;</code>
         *
         * @return The count of parameters.
         */
        public int getParametersCount() {
            return parameters_.size();
        }

        /**
         * <code>repeated bytes parameters = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The parameters at the given index.
         */
        public com.google.protobuf.ByteString getParameters(int index) {
            return parameters_.get(index);
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, className_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
            }
            for (int i = 0; i < parameterTypes_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, parameterTypes_.getRaw(i));
            }
            for (int i = 0; i < parameters_.size(); i++) {
                output.writeBytes(4, parameters_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(className_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, className_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < parameterTypes_.size(); i++) {
                    dataSize += computeStringSizeNoTag(parameterTypes_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getParameterTypesList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < parameters_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeBytesSizeNoTag(parameters_.get(i));
                }
                size += dataSize;
                size += 1 * getParametersList().size();
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof RpcRequestProto)) {
                return super.equals(obj);
            }
            RpcRequestProto other = (RpcRequestProto) obj;

            if (!getClassName()
                    .equals(other.getClassName())) return false;
            if (!getMethodName()
                    .equals(other.getMethodName())) return false;
            if (!getParameterTypesList()
                    .equals(other.getParameterTypesList())) return false;
            if (!getParametersList()
                    .equals(other.getParametersList())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
            hash = (53 * hash) + getClassName().hashCode();
            hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
            hash = (53 * hash) + getMethodName().hashCode();
            if (getParameterTypesCount() > 0) {
                hash = (37 * hash) + PARAMETERTYPES_FIELD_NUMBER;
                hash = (53 * hash) + getParameterTypesList().hashCode();
            }
            if (getParametersCount() > 0) {
                hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
                hash = (53 * hash) + getParametersList().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<RpcRequestProto> getParserForType() {
            return PARSER;
        }

        @Override
        public RpcRequestProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code cn.jiuyou2020.serialize.message.RpcRequestProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:cn.jiuyou2020.serialize.message.RpcRequestProto)
                RpcRequestProtoOrBuilder {
            private int bitField0_;
            private Object className_ = "";
            private Object methodName_ = "";
            private com.google.protobuf.LazyStringList parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private java.util.List<com.google.protobuf.ByteString> parameters_ = java.util.Collections.emptyList();

            // Construct using cn.jiuyou2020.serialize.message.protobuf.RpcRequestOuterClass.RpcRequestProto.newBuilder()
            private Builder() {

            }

            private Builder(
                    BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return RpcRequestOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return RpcRequestOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                RpcRequestProto.class, Builder.class);
            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                className_ = "";
                methodName_ = "";
                parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                parameters_ = java.util.Collections.emptyList();
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return RpcRequestOuterClass.internal_static_cn_jiuyou2020_serialize_message_RpcRequestProto_descriptor;
            }

            @Override
            public RpcRequestProto getDefaultInstanceForType() {
                return RpcRequestProto.getDefaultInstance();
            }

            @Override
            public RpcRequestProto build() {
                RpcRequestProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public RpcRequestProto buildPartial() {
                RpcRequestProto result = new RpcRequestProto(this);
                buildPartialRepeatedFields(result);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartialRepeatedFields(RpcRequestProto result) {
                if (((bitField0_ & 0x00000004) != 0)) {
                    parameterTypes_ = parameterTypes_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.parameterTypes_ = parameterTypes_;
                if (((bitField0_ & 0x00000008) != 0)) {
                    parameters_ = java.util.Collections.unmodifiableList(parameters_);
                    bitField0_ = (bitField0_ & ~0x00000008);
                }
                result.parameters_ = parameters_;
            }

            private void buildPartial0(RpcRequestProto result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.className_ = className_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.methodName_ = methodName_;
                }
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof RpcRequestProto) {
                    return mergeFrom((RpcRequestProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(RpcRequestProto other) {
                if (other == RpcRequestProto.getDefaultInstance()) return this;
                if (!other.getClassName().isEmpty()) {
                    className_ = other.className_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (!other.getMethodName().isEmpty()) {
                    methodName_ = other.methodName_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (!other.parameterTypes_.isEmpty()) {
                    if (parameterTypes_.isEmpty()) {
                        parameterTypes_ = other.parameterTypes_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureParameterTypesIsMutable();
                        parameterTypes_.addAll(other.parameterTypes_);
                    }
                    onChanged();
                }
                if (!other.parameters_.isEmpty()) {
                    if (parameters_.isEmpty()) {
                        parameters_ = other.parameters_;
                        bitField0_ = (bitField0_ & ~0x00000008);
                    } else {
                        ensureParametersIsMutable();
                        parameters_.addAll(other.parameters_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                className_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                methodName_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                String s = input.readStringRequireUtf8();
                                ensureParameterTypesIsMutable();
                                parameterTypes_.add(s);
                                break;
                            } // case 26
                            case 34: {
                                com.google.protobuf.ByteString v = input.readBytes();
                                ensureParametersIsMutable();
                                parameters_.add(v);
                                break;
                            } // case 34
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <pre>
             * New field for class type
             * </pre>
             *
             * <code>string className = 1;</code>
             *
             * @return The className.
             */
            public String getClassName() {
                Object ref = className_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    className_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * New field for class type
             * </pre>
             *
             * <code>string className = 1;</code>
             *
             * @param value The className to set.
             * @return This builder for chaining.
             */
            public Builder setClassName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                className_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * New field for class type
             * </pre>
             *
             * <code>string className = 1;</code>
             *
             * @return The bytes for className.
             */
            public com.google.protobuf.ByteString
            getClassNameBytes() {
                Object ref = className_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    className_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * New field for class type
             * </pre>
             *
             * <code>string className = 1;</code>
             *
             * @param value The bytes for className to set.
             * @return This builder for chaining.
             */
            public Builder setClassNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                className_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * New field for class type
             * </pre>
             *
             * <code>string className = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearClassName() {
                className_ = getDefaultInstance().getClassName();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>string methodName = 2;</code>
             *
             * @return The methodName.
             */
            public String getMethodName() {
                Object ref = methodName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    methodName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string methodName = 2;</code>
             *
             * @param value The methodName to set.
             * @return This builder for chaining.
             */
            public Builder setMethodName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                methodName_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string methodName = 2;</code>
             *
             * @return The bytes for methodName.
             */
            public com.google.protobuf.ByteString
            getMethodNameBytes() {
                Object ref = methodName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    methodName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string methodName = 2;</code>
             *
             * @param value The bytes for methodName to set.
             * @return This builder for chaining.
             */
            public Builder setMethodNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                methodName_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string methodName = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMethodName() {
                methodName_ = getDefaultInstance().getMethodName();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            private void ensureParameterTypesIsMutable() {
                if (!((bitField0_ & 0x00000004) != 0)) {
                    parameterTypes_ = new com.google.protobuf.LazyStringArrayList(parameterTypes_);
                    bitField0_ |= 0x00000004;
                }
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @return A list containing the parameterTypes.
             */
            public com.google.protobuf.ProtocolStringList
            getParameterTypesList() {
                return parameterTypes_.getUnmodifiableView();
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @return The count of parameterTypes.
             */
            public int getParameterTypesCount() {
                return parameterTypes_.size();
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @param index The index of the element to return.
             * @return The parameterTypes at the given index.
             */
            public String getParameterTypes(int index) {
                return parameterTypes_.get(index);
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @param index The index of the value to return.
             * @return The bytes of the parameterTypes at the given index.
             */
            public com.google.protobuf.ByteString
            getParameterTypesBytes(int index) {
                return parameterTypes_.getByteString(index);
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @param index The index to set the value at.
             * @param value The parameterTypes to set.
             * @return This builder for chaining.
             */
            public Builder setParameterTypes(
                    int index, String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParameterTypesIsMutable();
                parameterTypes_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @param value The parameterTypes to add.
             * @return This builder for chaining.
             */
            public Builder addParameterTypes(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParameterTypesIsMutable();
                parameterTypes_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @param values The parameterTypes to add.
             * @return This builder for chaining.
             */
            public Builder addAllParameterTypes(
                    Iterable<String> values) {
                ensureParameterTypesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, parameterTypes_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearParameterTypes() {
                parameterTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string parameterTypes = 3;</code>
             *
             * @param value The bytes of the parameterTypes to add.
             * @return This builder for chaining.
             */
            public Builder addParameterTypesBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureParameterTypesIsMutable();
                parameterTypes_.add(value);
                onChanged();
                return this;
            }

            private void ensureParametersIsMutable() {
                if (!((bitField0_ & 0x00000008) != 0)) {
                    parameters_ = new java.util.ArrayList<com.google.protobuf.ByteString>(parameters_);
                    bitField0_ |= 0x00000008;
                }
            }

            /**
             * <code>repeated bytes parameters = 4;</code>
             *
             * @return A list containing the parameters.
             */
            public java.util.List<com.google.protobuf.ByteString>
            getParametersList() {
                return ((bitField0_ & 0x00000008) != 0) ?
                        java.util.Collections.unmodifiableList(parameters_) : parameters_;
            }

            /**
             * <code>repeated bytes parameters = 4;</code>
             *
             * @return The count of parameters.
             */
            public int getParametersCount() {
                return parameters_.size();
            }

            /**
             * <code>repeated bytes parameters = 4;</code>
             *
             * @param index The index of the element to return.
             * @return The parameters at the given index.
             */
            public com.google.protobuf.ByteString getParameters(int index) {
                return parameters_.get(index);
            }

            /**
             * <code>repeated bytes parameters = 4;</code>
             *
             * @param index The index to set the value at.
             * @param value The parameters to set.
             * @return This builder for chaining.
             */
            public Builder setParameters(
                    int index, com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParametersIsMutable();
                parameters_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes parameters = 4;</code>
             *
             * @param value The parameters to add.
             * @return This builder for chaining.
             */
            public Builder addParameters(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParametersIsMutable();
                parameters_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes parameters = 4;</code>
             *
             * @param values The parameters to add.
             * @return This builder for chaining.
             */
            public Builder addAllParameters(
                    Iterable<? extends com.google.protobuf.ByteString> values) {
                ensureParametersIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, parameters_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated bytes parameters = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearParameters() {
                parameters_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:cn.jiuyou2020.serialize.message.RpcRequestProto)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
